---
title: "presentations"
format: html
---

conferences, presentations, & workshops... aka... where I've been & where to find me!

## 2026

-   **National Phenology Network Local Phenology Leader Virtual Conference**

    -   Oral Presentation: Creating a Seed Collection Calendar from NPN & LPP Data

## 2025

-   **Ecological Society of America Annual Meeting, Baltimore, MD**

    -   Oral Presentation: Higher Education & Native Seed Amplification: Vassar College’s Native Plant Propagation Program

-   [**Danbury Regional Pollinator Pathway Meeting**](https://www.wcsu.edu/stem/)

    -   Guest speaker, cultivating and preserving native plants through higher education

-   [**Nonbinary Botany**](https://nonbinarybotany.wordpress.com/about/) **Workshop**

-   **Northeast Natural History Conference, Springfield, MA**

    -   Session Organizer: Seed Amplification in the Northeast

        -   Speakers:

            -   Uli Lorimer

            -   Linda Rohleder

            -   Ethan Skuches

## 2024

-   [**EcoVisions: Finding Your Role in Environmentalism**](https://www.vassar.edu/institute/past-programs/2024-2025/ecovisions-finding-your-place-environmentalism)

    -   Conference Organizer

-   **Lower Hudson PRISM Quarterly Workshops**

-   **Northeast Natural History Conference, Albany, New York**

    -   Poster Presentation: Evaluating the Role of Arboreta in Invasive Plant Introductions: Insights from Vassar College

-   **National Native Seed Conference, Remote**		
